image: maven:3.8.7-openjdk-17

stages:
  - build
  - test
  - report

variables:
  MAVEN_CLI_OPTS: "-B -DskipTests"
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  script:
    - mvn test
  artifacts:
    paths:
      - target/surefire-reports/
      - test-output/ExtentReport.html

report:
  stage: report
  script:
    - echo "Test reports generated"
  artifacts:
    paths:
      - test-output/ExtentReport.html