name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests
        run: mvn clean test || true

      - name: Upload Surefire Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-test-results
          path: target/surefire-reports/

      - name: Upload Extent Report
        if: always()  # Ensure it runs even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: test-output/ExtentReport.html

      - name: Upload Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: target/cucumber-reports/